/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIsabellaRouteImport } from './routes/api/isabella'
import { Route as ApiIsabellaVoiceRouteImport } from './routes/api/isabella-voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaRoute = ApiIsabellaRouteImport.update({
  id: '/api/isabella',
  path: '/api/isabella',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaVoiceRoute = ApiIsabellaVoiceRouteImport.update({
  id: '/api/isabella-voice',
  path: '/api/isabella-voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/isabella': typeof ApiIsabellaRoute
  '/api/isabella-voice': typeof ApiIsabellaVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/isabella': typeof ApiIsabellaRoute
  '/api/isabella-voice': typeof ApiIsabellaVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/isabella': typeof ApiIsabellaRoute
  '/api/isabella-voice': typeof ApiIsabellaVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/isabella' | '/api/isabella-voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/isabella' | '/api/isabella-voice'
  id: '__root__' | '/' | '/api/isabella' | '/api/isabella-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiIsabellaRoute: typeof ApiIsabellaRoute
  ApiIsabellaVoiceRoute: typeof ApiIsabellaVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella': {
      id: '/api/isabella'
      path: '/api/isabella'
      fullPath: '/api/isabella'
      preLoaderRoute: typeof ApiIsabellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella-voice': {
      id: '/api/isabella-voice'
      path: '/api/isabella-voice'
      fullPath: '/api/isabella-voice'
      preLoaderRoute: typeof ApiIsabellaVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiIsabellaRoute: ApiIsabellaRoute,
  ApiIsabellaVoiceRoute: ApiIsabellaVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
